on: pull_request_review
name: Example Job
jobs:
  myJob:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: ./
      id: approved
      with:
        approvalsCount: '1'
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - run: echo "TEST"
    - run: echo "Approved !!"
      if: steps.approved.outputs.isApproved == 'true'
