name: Multi Approved Example Job
on:
  pull_request_review:
    types: [submitted]
jobs:
  onSubmit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ./
        id: approved
        with:
          approvalsCount: '2'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - run: echo "Approved 2 times."
        if: steps.approved.outputs.isApproved == 'true'
